# Generated by Django 3.0.4 on 2020-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
